SEG-46: Update segments when user rights changed
nedap/segnify-ios pull request #47
Opened 2022-07-06 12:43 UTC by tessagerritse

**Context**
- When user rights changed for viewing/creating reports, it is less confusing to update the data and segments when the client details are refreshed in addition to updating them when refreshing the client list. Changes to this package were needed to support updating the segments.

**Relevant issue**
- Closes #46 

**Changes**
- An update function is added to the page view controller and the segnicator is updated in the segnify view.

**Known problems**
- What problems do still arise or are anticipated?
- Which part of the solution do you need help with?

**Extra attention**
- What do I need to pay extra attention to as a reviewer?

**Check-list**
- [ ] Acceptance criteria described in the issue are satisfied, or the bug(s) is/are fixed.
- [ ] Documentation present (relevant information is properly documented).
- [ ] Written tests for test suite (optional).
- [ ] CHANGELOG updated.

**Tested on devices**
- [ ] Minimum supported iOS version.
- [ ] Maximum supported iOS version.
- [ ] Lowest resolution supported.
- [ ] Highest resolution supported.
- [ ] Device with a notch.

**Is this issue considered as Done?**
- [ ] It meets our [DoD](https://github.com/nedap/healthcare-mobile/wiki/DoD).

2022-07-07 07:45 UTC, dregatos requested changes
Hey @tessagerritse 

The code looks OK but I couldn't test the behaviour because the demo app is not running. Please, update the `MainViewController` 😊

<img width="500" alt="image_name" src="https://user-images.githubusercontent.com/4560667/177719839-3655c35f-14ca-403c-8758-4e51b6a88bf0.png">

2022-07-07 07:45 UTC, dregatos commented on Sources/Segnify/View Controllers/PageViewController.swift
> +    public func setDataSource(_ dataSource: SegnifyDataSourceProtocol?, shouldResetViewControllers: Bool) throws {
Please, document the new parameter.

2022-07-07 07:45 UTC, dregatos commented on Sources/Segnify/View Controllers/PageViewController.swift
> +            }
```suggestion
         if shouldResetViewControllers, dataSource!.contentElements.isEmpty == false {
            // Reset the view controllers of the page view controller.
            pageViewController.setViewControllers([dataSource!.contentElements.first!.viewController],
                                                  direction: .forward,
                                                  animated: false)
        
```

2022-07-07 07:45 UTC, dregatos commented on Sources/Segnify/View Controllers/PageViewController.swift
> +    public func updateContent(dataSource: SegnifyDataSourceProtocol?, segnifyConfigurator: SegnifyConfiguratorProtocol?) {
Please, document this public function.

2022-07-07 07:45 UTC, dregatos commented on Sources/Segnify/View Controllers/PageViewController.swift
> +            }
Could you please safely unwrap dataSource? I mean

```
guard let dataSource == dataSource {
            // Let the user know we're dealing with an invalid data source.
            throw SegnifyError.invalidDataSource
        }
```

instead of the `if dataSource == nil`.

2022-07-07 07:45 UTC, dregatos commented on Sources/Segnify/Views/Segnify.swift
> +        segnicatorWidthConstraint?.constant = segmentWidth
👍🏼

2022-07-18 07:52 UTC, dregatos reviewed
Hey @tessagerritse, welcome back!! 

Thank you for fixing the demo app. I was able to test it and it seems to adapt well to the new count of elements although, in the demo app, the width of the segments is not adjusted to the width of the screen (it does in Dossier).

<img width="250" alt="image_name" src="https://user-images.githubusercontent.com/4560667/179466966-9621abd5-fe8c-4431-83c4-9677b7aab5c7.png">

Also, when testing this branch on Dossier, I noticed that after enabling/disabling segments, the segment controller "lost the count". That's why I can't approve this PR although I'm not able to reproduce the issue in the demo app 🤔

2022-07-20 08:16 UTC, dregatos requested changes
Hey @tessagerritse,

Not sure what happened but I'm still able to reproduce both issues:

1. In the demo app, the width of the segments is not adjusted to the screen's width (like in Dossier). Not critical, but it would be great to have an example about how to do that in the demo app.

<img width="300" alt="image_name" src="https://user-images.githubusercontent.com/4560667/179930560-f27dc44c-ecbf-49bf-90e0-60c6af20c66e.png">

2. The critical one is also still happening, although now it seems harder to reproduce. When swiping to change the section, at some point, the segment is not synced anymore with the page controller.


https://user-images.githubusercontent.com/4560667/179932515-52fb59d0-e3dd-4503-ae28-c17a8dbf4b82.mov

2022-07-20 09:08 UTC, tessagerritse commented
Hi @dregatos, thanks for your feedback. Sorry for ignoring your first issue, I didn't pick it up as something for me to fix cause it's just not something available in the demo app, to begin with. But I think it's a good idea to show it as an example. Therefore, I didn't replace the existing segnifyConfigurator file to show different ways of implementing the protocol. I implemented the second one similar to how it is in Dossier. See what you think.
The second issue is giving me a headache 😢. Not sure what is happening and didn't notice it myself, but I'll try to debug again

2022-08-02 07:55 UTC, tessagerritse commented
Hey, @ymykhailova I tested these changes on develop and on the base branch of the rights feature and everything seems to work fine. Could you please check and review it? 😇

2022-08-02 14:47 UTC, ymykhailova reviewed
Hey Tessa, thanks for improving this component! 🎉 It needed this feature :)
Everything works fine except for one thing: when there is only one segment it is still possible to swipe between sections, which results in an empty screen. Can we just disable swipe when there is only one section? See video 👇 

https://user-images.githubusercontent.com/54804428/182402268-d0056a58-1139-4339-8064-a99a25bde1f6.mp4

2022-08-02 14:47 UTC, ymykhailova commented on iOS Example/Swift Package Manager/Segnified/View Controllers/MainViewController.swift
> +        }
hehe, a bit ugly, but hey it's a test app :P

2022-08-02 14:47 UTC, ymykhailova commented on iOS Example/Swift Package Manager/Segnified/View Controllers/MainViewController.swift
> +        textLabel.text = "Gorgeous banner view!"
❤️

2022-08-02 19:18 UTC, ymykhailova approved these changes
Works like a charm! I only left a small suggestion

2022-08-02 19:18 UTC, ymykhailova commented on Sources/Segnify/View Controllers/PageViewController.swift
> +                }
How about some space-saving?
```suggestion
                scrollView.isScrollEnabled = (dataSource?.contentElements.count > 1)
```

2022-08-03 05:15 UTC, tessagerritse commented on Sources/Segnify/View Controllers/PageViewController.swift
> +                }
Nice, I felt like it could be simpler, but changed around a lot and couldn't quite find the right one 😅

2022-08-04 07:57 UTC, merged