SEG-2: SwiftLint 🫶
nedap/segnify-ios pull request #55
Opened 2023-05-19 14:04 UTC by RobinCPel

## Context

Linting is important, cause the code style needs to be purrrfect.

## Relevant issue

Closes #2 

## Changes

- Adds SwiftLint;
- Adds a slightly modified version of Theia's SwiftLint configuration;
- Fixes one SwiftLint error;
- Fixes A LOT of SwiftLint warnings.

## Known problems

I left some SwiftLint warnings cause I'm not sure what to do with them / if it would break stuff 👉👈

## Extra attention

When you hit `cmd + b` it should just build (the "Segnify" target) and also run the SwiftLint plugin.
But it's possible that it fails, I had to set the path for the active developer directory of the Xcode command line developer tools to `/Applications/Xcode.app/Contents/Developer`. If this is an issue on every device, then we'll need to come up with a good solution for it ✨

## Side notes

The changes should probably also be tested inside one of our apps that uses Segnify intensively - can we create a pre-release or something to achieve this?

2023-05-24 07:26 UTC, dregatos requested changes
Thanks @RobinCPel for making it possible to lint the code in this package 🥳 I left a comment regarding how it should be integrated and I also think that these warnings can be easily avoided...

<img width="300" alt="image_name" src="https://github.com/nedap/segnify-ios/assets/4560667/c14ee7a9-d9e0-4e02-9efe-11e8a88b50c1">

Ah! and I pushed two commits. Please, take a look :)

2023-05-25 08:09 UTC, RobinCPel commented on Package.swift
> +        .package(url: "https://github.com/realm/SwiftLint.git", "0.52.0"..<"0.53.0")
Yeah, this part from what you linked: `To do this select the project in the file navigator, then select the primary app target, and go to Build Phases.` doesn't work since there is no project file (because Segnify is not a project, it's a package) 😅

2023-05-25 09:19 UTC, RobinCPel commented on Package.swift
> +        .package(url: "https://github.com/realm/SwiftLint.git", "0.52.0"..<"0.53.0")
I read some more into it ([this video is quite nice](https://developer.apple.com/videos/play/wwdc2022/110359/)), and I really believe that the current way (with the plugin) is the right one.
The only thing I'm not certain of, is whether the extra dependencies are included in the build and thus required by the consuming Xcode project (e.g. Dossier). 🤔

2023-06-07 06:03 UTC, dregatos requested changes
Hey @tessagerritse,

I noticed two issues:

1. Unit tests are not executed
2. SwiftLint is not really listing the code. Try to force a warning and check if it really appears in the logs... I believe that the problem is that now that we are using the demo app to running the analysis, the `.swiftlint.yml` needs to be moved to the demo app folder. Otherwise, the rules are unknown.

2023-06-08 09:04 UTC, dregatos approved these changes
Thank you @tessagerritse  for taking care of this one 😇

2023-06-08 09:29 UTC, merged